baseurl = "/"
languageCode = "en-us"
title = "Casa Carmen Cafe"

[params]
  description = "Eat all you can for FREE!!!"

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1
[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 4
